# Generated by Django 4.0.3 on 2022-04-09 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('Электронная версия', 'e-version'), ('Бумажная книга', 'print version')], default='Бумажная книга', max_length=50, verbose_name='Статус')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Статья', 'статья'), ('Дипломная работа', 'дипломная работа'), ('Книга', 'книга')], default='Статья', max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('На списание', 'На списание'), ('На закупку', 'На закупку')], default='На закупку', max_length=20)),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Одобрена', 'Одобрена'), ('Отклонена', 'Отклонена')], default='На рассмотрении', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=255, verbose_name='ИИН')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент:')),
            ],
        ),
        migrations.CreateModel(
            name='thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=255, verbose_name='Название темы на Каз:')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название темы на RU:')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название темы на ENG:')),
                ('descname_kz', models.CharField(max_length=255, verbose_name='Описание темы на Каз:')),
                ('descname_ru', models.CharField(max_length=255, verbose_name='Описание темы на RU:')),
                ('descname_eng', models.CharField(max_length=255, verbose_name='Описание темы на ENG:')),
                ('count_stud', models.IntegerField(default=5, verbose_name='Кол-во допустимых студентов')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.student', verbose_name='ФИО - Cтудента:')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=255, verbose_name='ИИН')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_books', to='webapp.book', verbose_name='Книга')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_books', to='webapp.request', verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Издатель')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользыватель')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Принят', 'Принят'), ('Отменён', 'Отменён')], default='Новый', max_length=20, verbose_name='Статус')),
                ('book', models.ManyToManyField(related_name='order_books', to='webapp.requestbook', verbose_name='Книга')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='webapp.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='webapp.publisher'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема:')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последний изм.')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='Категория')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.staff', verbose_name='Преподаватель')),
            ],
        ),
    ]
